@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjAxNDI4ODQsImV4cCI6MTc2MDE3MTY4NH0.Q4Xs47_rXbTc4CcKmU2Wn_KevqjVvqAJK37X8OJh-d4

### Criar um novo usuário
POST http://localhost:4000/customers HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "teste1",
    "cnpj": "12345678000198",
    "contact": "16992455837",
    "email": "Customertest@gmail.com",
    "address": "Rua teste, 123",
    "modality": "Atacado"
}

### Criar um novo usuário
GET http://localhost:4000/customers HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:4000/customers/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Nome teste",
    "cnpj": "12345678000195",
    "contact": "16992455837",
    "email": "Customerteste@gmail.com",
    "address": "Rua teste, 123",
    "note": "Cliente geralmente pede as terças",
    "modality": "Atacado"
}