@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoid2lsc29uQGVtcHJlc2EuY29tIiwibmFtZSI6IldpbHNvbiIsImlhdCI6MTc1OTk2NTMzNywiZXhwIjoxNzU5OTk0MTM3fQ.7AjXeKEzp0ky-KHTP8GezTjLvgjJ0u4F3yYEgyrNDKo

###
POST http://localhost:3000/fixedExpenses HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "description": "Aluguel",
  "value": 900,
  "recurring": true,
  "category": "Serviços",
  "note": "Plano mensal de internet"
}

###
GET http://localhost:3000/fixedExpenses HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/fixedExpenses HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/fixedExpenses/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/fixedExpenses/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "description": "Internet",
  "value": 120.50,
  "recurring": true,
  "category": "Serviços",
  "note": "Plano mensal de internet"
}

###
DELETE  http://localhost:3000/fixedExpenses HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}