@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NTk1MTI3NzAsImV4cCI6MTc1OTU0MTU3MH0.25mQra6HHJKbQQCfctQHNFQjTGtKwXy3Vw60NSQUFS8

###
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "customerId": 3,
  "orderDate": "2025-10-03",
  "deliveryDate": "2025-10-06",
  "status": "PENDING",
  "notes": "Entrega para terca-feira"
}

###
PUT http://localhost:3000/orders/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "customerId": 1,
  "orderDate": "2025-10-02",
  "deliveryDate": "2025-10-06",
  "status": "PENDING",
  "notes": "Entrega rápida"
}


###
GET http://localhost:3000/orders/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/orders/1/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": 4,
  "quantity": 2
}
###
DELETE http://localhost:3000/orders/1/items/2
Content-Type: application/json
Authorization: Bearer {{token}}
