@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjMxNDk4NTYsImV4cCI6MTc2MzE4NTg1Nn0.K1GJ8oyqBG5Iwf7iLPf46avhkNNWgPR7ZBnBArZzyGU

###
POST http://localhost:4000/orders HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "customerId": 1,
  "orderDate": "2025-10-04",
  "deliveryDate": "2025-10-06",
  "status": "PENDENTE",
  "notes": "Entrega para segunda-feira",
  "items": [
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}

###
PUT http://localhost:4000/orders/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "customerId": 1,
  "orderDate": "2025-10-02",
  "deliveryDate": "2025-10-06",
  "status": "PENDENTE",
  "notes": "Entrega rápida"
}


###
GET http://localhost:4000/orders HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:4000/orders/1/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": 3,
  "quantity": 2
}
###
DELETE http://localhost:4000/orders/1/items/2
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:4000/orders/1/items/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": 1,
  "quantity": 8
}

###
PUT http://localhost:4000/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "EM PRODUÇÃO"
}