@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NTk0MzM1MjksImV4cCI6MTc1OTQ2MjMyOX0.Q2TdGnHwEfSzr54KmwRKxRItEnai6PvJV78fboVMu7A

###
POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bolo de chocolate",
  "description": "Bolo de chocolate nobre",
  "category": "BOLOS",
  "costPrice": 10.90,
  "markupPercent": 100,
  "salePrice": 21.8,
  "stockQuantity": 10,
  "isActive": true
}

###
GET http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/products/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bolo de fuba",
  "description": "Bolo de fuba quentinho",
  "category": "BOLOS",
  "costPrice": 7.90,
  "markupPercent": 100,
  "salePrice": 15.8,
  "stockQuantity": 10,
  "isActive": true
}
