@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NTk1MTI3NzAsImV4cCI6MTc1OTU0MTU3MH0.25mQra6HHJKbQQCfctQHNFQjTGtKwXy3Vw60NSQUFS8

###
POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bolo de pistache",
  "description": "Bolo de chocolate nobre",
  "category": "BOLOS",
  "costPrice": 15.90,
  "markupPercent": 120,
  "stockQuantity": 10,
  "isActive": true
}

###
GET http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/products/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dolce di Pistacchio",
  "description": "Bolo macio de pistache com recheio cremoso de ganache de pistache, finalizado com cobertura sedosa e pistaches torrados crocantes.",
  "category": "BOLOS",
  "costPrice": 15,
  "markupPercent": 130,
  "stockQuantity": 10,
  "isActive": true
}
