@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjE5Mjg5NDcsImV4cCI6MTc2MTk1Nzc0N30.F0QY6PvulM2raj3HmgzAK4aswsUrCISu43tetEdJ2Fo

###
POST http://localhost:4000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bolo de manga",
  "costPrice": 120,
  "markupPercent": 120,
  "stockQuantity": 12,
  "category": "BOLOS",
  "fotoData": "",
}

# {
#   "name": "Dolce di Pistacchio",
#   "description": "Bolo macio de pistache com recheio cremoso de ganache de pistache, finalizado com cobertura sedosa e pistaches torrados crocantes.",
#   "category": "BOLOS",
#   "costPrice": 15.90,
#   "markupPercent": 120,
#   "stockQuantity": 10,
#   "isActive": true
# }


###
GET http://localhost:4000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:4000/products/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dolce di Pistacchio",
  "description": "Bolo macio de pistache com recheio cremoso de ganache de pistache, finalizado com cobertura sedosa e pistaches torrados crocantes.",
  "category": "BOLOS",
  "costPrice": 17,
  "markupPercent": 130,
  "stockQuantity": 10,
  "isActive": true
}

###
PUT http://localhost:4000/products/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "stockQuantity": 10
}
