### Cria / Registra uma compra de suprimentos
POST http://localhost:3000/supplyPurchase
Content-Type: application/json

{
    "supplier": "Fornecedor Exemplo",
    "PaymentMethod": "Cartão de Crédito",
    "total": 1500.00,
    "note,": "Compra mensal de suprimentos",
}

### Lista todas as compras de suprimentos
GET http://localhost:3000/supplyPurchase
Content-Type: application/json


### Atualiza uma compra de suprimentos pelo ID
PUT http://localhost:3000/supplyPurchase/1
Content-Type: application/json

{
    "supplier": "Fornecedor Atualizado",
    "paymentMethod": "Boleto Bancário",
    "total": 1750.00,
    "note": "Compra atualizada de suprimentos"
}

### Deleta uma compra de suprimentos pelo ID
DELETE http://localhost:3000/supplyPurchase/1
Content-Type: application/json