@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjAwMzc0NzYsImV4cCI6MTc2MDA2NjI3Nn0.BAfz6nDLsGROoPpOJ1PcXF3LO_MOFxjn4Abd7IshBek

###
POST http://localhost:4000/supply HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "description": "saco de farinha",
  "name": "farinha",
  "unit": "kg",
  "unitPrice": 10.00,
  "stockQty": 5
}

###
GET http://localhost:4000/supply HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:4000/supply/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:4000/supply/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
 "description": "Aluguel",
  "name": "Bolo de chocolate",
  "unit": "cladio",
  "unitPrice": 120.00,
  "stockyQty": 5
}

###
DELETE  http://localhost:4000/supply/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###


