@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjAwMzc0NzYsImV4cCI6MTc2MDA2NjI3Nn0.BAfz6nDLsGROoPpOJ1PcXF3LO_MOFxjn4Abd7IshBek

### Cria / Registra uma compra de suprimentos
POST http://localhost:3000/supplyPurchases
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "supplier": "Fornecedor Exemplo",
    "paymentMethod": "Cartão de Crédito",
    "note,": "Compra mensal de suprimentos"
}

### Lista todas as compras de suprimentos
GET http://localhost:3000/supplyPurchases/
Content-Type: application/json
Authorization: Bearer {{token}}

### Lista todas as compras de suprimentos
GET http://localhost:3000/supplyPurchases/2
Content-Type: application/json
Authorization: Bearer {{token}}


### Atualiza uma compra de suprimentos pelo ID
PUT http://localhost:3000/supplyPurchases/1
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "supplier": "Fornecedor Atualizado",
    "paymentMethod": "Boleto Bancário",
    "total": 1750.00,
    "note": "Compra atualizada de suprimentos"
}

### Deleta uma compra de suprimentos pelo ID
DELETE http://localhost:3000/supplyPurchase/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/supplyPurchases/2/items HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "supplyId": 1,
  "quantity": 5
}

###
GET http://localhost:3000/supplyPurchases/1/items HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}