@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtQGdtYWlsLmNvbSIsIm5hbWUiOiJhZG0iLCJpYXQiOjE3NjAwMzIyMTksImV4cCI6MTc2MDA2MTAxOX0.iOyTpGiC_MlPmrjCGh6GvRnzQk7qo9GOcTyH1r7laPc

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Wilson",
  "email": "wilson@empresa.com",
  "password": "wil@123",
  "phone": "16999999999",
  "groupIds": [2]
}


###
GET http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


###
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "adm@gmail.com",
  "senha": "Adm@123"
}

###
PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "adm8",
  "email": "teste8@gmail.com",
  "password": "teste8",
  "phone": "16992455837",
  "permission": false
}

###
DELETE http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
